[package]
name = "fontsubset-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "GPUI frontend for fontsubset-core"

[[bin]]
name = "fontsubset-gui"
path = "src/main.rs"
test = false

[dependencies]
fontsubset-core = { path = "../fontsubset-core" }
parking_lot.workspace = true
rfd.workspace = true
gpui-kit = { version = "0.6.0", default-features = false, features = ["component", "assets"] }
