[package]
name = "fontsubset-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "GPUI frontend for fontsubset-core"

[[bin]]
name = "fontsubset-gui"
path = "src/main.rs"
test = false

[dependencies]
fontsubset-core = { path = "../fontsubset-core" }
parking_lot.workspace = true
rfd.workspace = true
gpui = { package = "gpui-pre", version = "0.3.3" }
gpui_platform = { package = "gpui-pre-platform", version = "0.3.3" }
gpui-component = "0.6.0"
gpui-component-assets = { package = "gpui-kit-assets", version = "0.6.0" }
