// Copyright 2012 Google Inc. All Rights Reserved.

namespace com.google.typography.font.sfntly.table.opentype;






/**
 * @author dougfelt@google.com (Doug Felt)
 */
public sealed class LanguageTag : ClassEnumBase<LanguageTag>
{
    public static readonly LanguageTag
  ABA = new("Abaza", "abq"),
  ABK = new("Abkhazian", "abk"),
  ADY = new("Adyghe", "ady"),
  AFK = new("Afrikaans", "afr"),
  AFR = new("Afar", "aar"),
  AGW = new("Agaw", "ahg"),
  ALS = new("Alsatian", "gsw"),
  ALT = new("Altai", "atv,alt"),
  AMH = new("Amharic", "amh"),
  APPH = new("Phonetic transcription—Americanist conventions", ""),
  ARA = new("Arabic", "ara"),
  ARI = new("Aari", "aiw"),
  ARK = new("Arakanese", "mhv,rmz,rki"),
  ASM = new("Assamese", "asm"),
  ATH = new("Athapaskan", "apk,apj,apl,apm,apw,nav,bea,sek,bcr,caf,crx,clc,gwi,haa,chp,dgr,scs,xsl,srs,ing,hoi,koy,hup,ktw,mvb,wlk,coq,ctc,gce,tol,tuu,kkz,tgx,tht,aht,tfn,taa,tau,tcb,kuu,tce,ttm,txc"),
  AVR = new("Avar", "ava"),
  AWA = new("Awadhi", "awa"),
  AYM = new("Aymara", "aym"),
  AZE = new("Azeri", "aze"),
  BAD = new("Badaga", "bfq"),
  BAG = new("Baghelkhandi", "bfy"),
  BAL = new("Balkar", "krc"),
  BAU = new("Baule", "bci"),
  BBR = new("Berber", ""),
  BCH = new("Bench", "bcq"),
  BCR = new("Bible Cree", ""),
  BEL = new("Belarussian", "bel"),
  BEM = new("Bemba", "bem"),
  BEN = new("Bengali", "ben"),
  BGR = new("Bulgarian", "bul"),
  BHI = new("Bhili", "bhi,bhb"),
  BHO = new("Bhojpuri", "bho"),
  BIK = new("Bikol", "bik"),
  BIL = new("Bilen", "byn"),
  BKF = new("Blackfoot", "bla"),
  BLI = new("Balochi", "bal"),
  BLN = new("Balante", "bjt,ble"),
  BLT = new("Balti", "bft"),
  BMB = new("Bambara", "bam"),
  BML = new("Bamileke", ""),
  BOS = new("Bosnian", "bos"),
  BRE = new("Breton", "bre"),
  BRH = new("Brahui", "brh"),
  BRI = new("Braj Bhasha", "bra"),
  BRM = new("Burmese", "mya"),
  BSH = new("Bashkir", "bak"),
  BTI = new("Beti", "btb"),
  CAT = new("Catalan", "cat"),
  CEB = new("Cebuano", "ceb"),
  CHE = new("Chechen", "che"),
  CHG = new("Chaha Gurage", "sgw"),
  CHH = new("Chattisgarhi", "hne"),
  CHI = new("Chichewa", "nya"),
  CHK = new("Chukchi", "ckt"),
  CHN = new("Chinese -- as seen in win7 kaiu.ttf", "zho"),
  CHP = new("Chipewyan", "chp"),
  CHR = new("Cherokee", "chr"),
  CHU = new("Chuvash", "chv"),
  CMR = new("Comorian", "swb,wlc,wni,zdj"),
  COP = new("Coptic", "cop"),
  COS = new("Corsican", "cos"),
  CRE = new("Cree", "cre"),
  CRR = new("Carrier", "crx,caf"),
  CRT = new("Crimean Tatar", "crh"),
  CSL = new("Church Slavonic", "chu"),
  CSY = new("Czech", "ces"),
  DAN = new("Danish", "dan"),
  DAR = new("Dargwa", "dar"),
  DCR = new("Woods Cree", "cwd"),
  DEU = new("German", "deu"),
  DFLT = new("default", ""),
  DGR = new("Dogri", "doi"),
  DHV = new("Dhivehi", "div"), // deprecated
  DIV = new("Dhivehi", "div"),
  DJR = new("Djerma", "dje"),
  DNG = new("Dangme", "ada"),
  DNK = new("Dinka", "din"),
  DRI = new("Dari", "prs"),
  DUN = new("Dungan", "dng"),
  DZN = new("Dzongkha", "dzo"),
  EBI = new("Ebira", "igb"),
  ECR = new("Eastern Cree", "crj,crl"),
  EDO = new("Edo", "bin"),
  EFI = new("Efik", "efi"),
  ELL = new("Greek", "ell"),
  ENG = new("English", "eng"),
  ERZ = new("Erzya", "myv"),
  ESP = new("Spanish", "spa"),
  ETI = new("Estonian", "est"),
  EUQ = new("Basque", "eus"),
  EVK = new("Evenki", "evn"),
  EVN = new("Even", "eve"),
  EWE = new("Ewe", "ewe"),
  FAN = new("French Antillean", "acf"),
  FAR = new("Farsi", "fas"),
  FIN = new("Finnish", "fin"),
  FJI = new("Fijian", "fij"),
  FLE = new("Flemish", "vls"),
  FNE = new("Forest Nenets", "enf"),
  FON = new("Fon", "fon"),
  FOS = new("Faroese", "fao"),
  FRA = new("French", "fra"),
  FRI = new("Frisian", "fry"),
  FRL = new("Friulian", "fur"),
  FTA = new("Futa", "fuf"),
  FUL = new("Fulani", "ful"),
  GAD = new("Ga", "gaa"),
  GAE = new("Gaelic", "gla"),
  GAG = new("Gagauz", "gag"),
  GAL = new("Galician", "glg"),
  GAR = new("Garshuni", ""),
  GAW = new("Garhwali", "gbm"),
  GEZ = new("Ge'ez", "gez"),
  GIL = new("Gilyak", "niv"),
  GMZ = new("Gumuz", "guk"),
  GON = new("Gondi", "gon"),
  GRN = new("Greenlandic", "kal"),
  GRO = new("Garo", "grt"),
  GUA = new("Guarani", "grn"),
  GUJ = new("Gujarati", "guj"),
  HAI = new("Haitian", "hat"),
  HAL = new("Halam", "flm"),
  HAR = new("Harauti", "hoj"),
  HAU = new("Hausa", "hau"),
  HAW = new("Hawaiin", "haw"),
  HBN = new("Hammer-Banna", "amf"),
  HIL = new("Hiligaynon", "hil"),
  HIN = new("Hindi", "hin"),
  Mari = new("High", "HMA     mrj"),
  HND = new("Hindko", "hno,hnd"),
  HO = new("Ho", "hoc"),
  HRI = new("Harari", "har"),
  HRV = new("Croatian", "hrv"),
  HUN = new("Hungarian", "hun"),
  HYE = new("Armenian", "hye"),
  IBO = new("Igbo", "ibo"),
  IJO = new("Ijo", "ijc"),
  ILO = new("Ilokano", "ilo"),
  IND = new("Indonesian", "ind"),
  ING = new("Ingush", "inh"),
  INU = new("Inuktitut", "iku"),
  IPPH = new("Phonetic transcription—IPA conventions", ""),
  IRI = new("Irish", "gle"),
  IRT = new("Irish Traditional", "gle"),
  ISL = new("Icelandic", "isl"),
  ISM = new("Inari Sami", "smn"),
  ITA = new("Italian", "ita"),
  IWR = new("Hebrew", "heb"),
  JAV = new("Javanese", "jav"),
  JII = new("Yiddish", "yid"),
  JAN = new("Japanese", "jpn"),
  JUD = new("Judezmo", "lad"),
  JUL = new("Jula", "dyu"),
  KAB = new("Kabardian", "kbd"),
  KAC = new("Kachchi", "kfr"),
  KAL = new("Kalenjin", "kln"),
  KAN = new("Kannada", "kan"),
  KAR = new("Karachay", "krc"),
  KAT = new("Georgian", "kat"),
  KAZ = new("Kazakh", "kaz"),
  KEB = new("Kebena", "ktb"),
  KGE = new("Khutsuri Georgian", "kat"),
  KHA = new("Khakass", "kjh"),
  KHK = new("Khanty-Kazim", "kca"),
  KHM = new("Khmer", "khm"),
  KHN = new("Khun(?)", "kkh"),
  KHS = new("Khanty-Shurishkar", "kca"),
  KHV = new("Khanty-Vakhi", "kca"),
  KHW = new("Khowar", "khw"),
  KIK = new("Kikuyu", "kik"),
  KIR = new("Kirghiz", "kir"),
  KIS = new("Kisii", "kqs,kss"),
  KKN = new("Kokni", "kex"),
  KLM = new("Kalmyk", "xal"),
  KMB = new("Kamba", "kam"),
  KMN = new("Kumaoni", "kfy"),
  KMO = new("Komo", "kmw"),
  KMS = new("Komso", "kxc"),
  KNR = new("Kanuri", "kau"),
  KOD = new("Kodagu", "kfa"),
  KOH = new("Korean Old Hangul", "okm"),
  KOK = new("Konkani", "kok"),
  KON = new("Kikongo", "ktu"),
  KOP = new("Komi-Permyak", "koi"),
  KOR = new("Korean", "kor"),
  KOZ = new("Komi-Zyrian", "kpv"),
  KPL = new("Kpelle", "kpe"),
  KRI = new("Krio", "kri"),
  KRK = new("Karakalpak", "kaa"),
  KRL = new("Karelian", "krl"),
  KRM = new("Karaim", "kdr"),
  KRN = new("Karen", "kar"),
  KRT = new("Koorete", "kqy"),
  KSH = new("Kashmiri", "kas"),
  KSI = new("Khasi", "kha"),
  KSM = new("Kildin Sami", "sjd"),
  KUI = new("Kui", "kxu"),
  KUL = new("Kulvi", "kfx"),
  KUM = new("Kumyk", "kum"),
  KUR = new("Kurdish", "kur"),
  KUU = new("Kurukh", "kru"),
  KUY = new("Kuy", "kdt"),
  KYK = new("Koryak", "kpy"),
  LAD = new("Ladin", "lld"),
  LAH = new("Lahuli", "bfu"),
  LAK = new("Lak", "lbe"),
  LAM = new("Lambani", "lmn"),
  LAO = new("Lao", "lao"),
  LAT = new("Latin", "lat"),
  LAZ = new("Laz", "lzz"),
  LCR = new("L-Cree", "crm"),
  LDK = new("Ladakhi", "lbj"),
  LEZ = new("Lezgi", "lez"),
  LIN = new("Lingala", "lin"),
  LMA = new("Low Mari", "mhr"),
  LMB = new("Limbu", "lif"),
  LMW = new("Lomwe", "ngl"),
  LSB = new("Lower Sorbian", "dsb"),
  LSM = new("Lule Sami", "smj"),
  LTH = new("Lithuanian", "lit"),
  LTZ = new("Luxembourgish", "ltz"),
  LUB = new("Luba", "lua,lub"),
  LUG = new("Luganda", "lug"),
  LUH = new("Luhya", "luy"),
  LUO = new("Luo", "luo"),
  LVI = new("Latvian", "lav"),
  MAJ = new("Majang", "mpe"),
  MAK = new("Makua", "vmw"),
  MAL = new("Malayalam Traditional", "mal"),
  MAN = new("Mansi", "mns"),
  MAP = new("Mapudungun", "arn"),
  MAR = new("Marathi", "mar"),
  MAW = new("Marwari", "mwr"),
  MBN = new("Mbundu", "kmb"),
  MCH = new("Manchu", "mnc"),
  MCR = new("Moose Cree", "crm"),
  MDE = new("Mende", "men"),
  MEN = new("Me'en", "mym"),
  MIZ = new("Mizo", "lus"),
  MKD = new("Macedonian", "mkd"),
  MLE = new("Male", "mdy"),
  MLG = new("Malagasy", "mlg"),
  MLN = new("Malinke", "mlq"),
  MLR = new("Malayalam Reformed", "mal"),
  MLY = new("Malay", "msa"),
  MND = new("Mandinka", "mnk"),
  MNG = new("Mongolian", "mon"),
  MNI = new("Manipuri", "mni"),
  MNK = new("Maninka", "man"),
  MNX = new("Manx Gaelic", "glv"),
  MOH = new("Mohawk", "moh"),
  MOK = new("Moksha", "mdf"),
  MOL = new("Moldavian", "mol"),
  MON = new("Mon", "mnw"),
  MOR = new("Moroccan", ""),
  MRI = new("Maori", "mri"),
  MTH = new("Maithili", "mai"),
  MTS = new("Maltese", "mlt"),
  MUN = new("Mundari", "unr"),
  NAG = new("Naga-Assamese", "nag"),
  NAN = new("Nanai", "gld"),
  NAS = new("Naskapi", "nsk"),
  NCR = new("N-Cree", "csw"),
  NDB = new("Ndebele", "nbl,nde"),
  NDG = new("Ndonga", "ndo"),
  NEP = new("Nepali", "nep"),
  NEW = new("Newari", "new"),
  NGR = new("Nagari", ""),
  NHC = new("Norway House Cree", "csw"),
  NIS = new("Nisi", "dap"),
  NIU = new("Niuean", "niu"),
  NKL = new("Nkole", "nyn"),
  NKO = new("N'Ko", "nqo"),
  NLD = new("Dutch", "nld"),
  NOG = new("Nogai", "nog"),
  NOR = new("Norwegian", "nob"),
  NSM = new("Northern Sami", "sme"),
  NTA = new("Northern Tai", "nod"),
  NTO = new("Esperanto", "epo"),
  NYN = new("Nynorsk", "nno"),
  OCI = new("Occitan", "oci"),
  OCR = new("Oji-Cree", "ojs"),
  OJB = new("Ojibway", "oji"),
  ORI = new("Odia (formerly Oriya)", "ori"),
  ORO = new("Oromo", "orm"),
  OSS = new("Ossetian", "oss"),
  PAA = new("Palestinian Aramaic", "sam"),
  PAL = new("Pali", "pli"),
  PAN = new("Punjabi", "pan"),
  PAP = new("Palpa", "plp"),
  PAS = new("Pashto", "pus"),
  PGR = new("Polytonic Greek", "ell"),
  PIL = new("Filipino", "fil"),
  PLG = new("Palaung", "pce,rbb,pll"),
  PLK = new("Polish", "pol"),
  PRO = new("Provencal", "pro"),
  PTG = new("Portuguese", "por"),
  QIN = new("Chin", "bgr,cnh,cnw,czt,sez,tcp,csy,ctd,flm,pck,tcz,zom,cmr,dao,hlt,cka,cnk,mrh,mwg,cbl,cnb,csh"),
  RAJ = new("Rajasthani", "raj"),
  RCR = new("R-Cree", "atj"),
  RBU = new("Russian Buriat", "bxr"),
  RIA = new("Riang", "ria"),
  RMS = new("Rhaeto-Romanic", "roh"),
  ROM = new("Romanian", "ron"),
  ROY = new("Romany", "rom"),
  RSY = new("Rusyn", "rue"),
  RUA = new("Ruanda", "kin"),
  RUS = new("Russian", "rus"),
  SAD = new("Sadri", "sck"),
  SAN = new("Sanskrit", "san"),
  SAT = new("Santali", "sat"),
  SAY = new("Sayisi", "chp"),
  SEK = new("Sekota", "xan"),
  SEL = new("Selkup", "sel"),
  SGO = new("Sango", "sag"),
  SHN = new("Shan", "shn"),
  SIB = new("Sibe", "sjo"),
  SID = new("Sidamo", "sid"),
  SIG = new("Silte Gurage", "xst"),
  SKS = new("Skolt Sami", "sms"),
  SKY = new("Slovak", "slk"),
  SLA = new("Slavey", "scs"),
  SLV = new("Slovenian", "slv"),
  SML = new("Somali", "som"),
  SMO = new("Samoan", "smo"),
  SNA = new("Sena", "she"),
  SND = new("Sindhi", "snd"),
  SNH = new("Sinhalese", "sin"),
  SNK = new("Soninke", "snk"),
  SOG = new("Sodo Gurage", "gru"),
  SOT = new("Sotho", "nso,sot"),
  SQI = new("Albanian", "sqi"),
  SRB = new("Serbian", "srp"),
  SRK = new("Saraiki", "skr"),
  SRR = new("Serer", "srr"),
  SSL = new("South Slavey", "xsl"),
  SSM = new("Southern Sami", "sma"),
  SUR = new("Suri", "suq"),
  SVA = new("Svan", "sva"),
  SVE = new("Swedish", "swe"),
  SWA = new("Swadaya Aramaic", "aii"),
  SWK = new("Swahili", "swa"),
  SWZ = new("Swazi", "ssw"),
  SXT = new("Sutu", "ngo"),
  SYR = new("Syriac", "syr"),
  TAB = new("Tabasaran", "tab"),
  TAJ = new("Tajiki", "tgk"),
  TAM = new("Tamil", "tam"),
  TAT = new("Tatar", "tat"),
  TCR = new("TH-Cree", "cwd"),
  TEL = new("Telugu", "tel"),
  TGN = new("Tongan", "ton"),
  TGR = new("Tigre", "tig"),
  TGY = new("Tigrinya", "tir"),
  THA = new("Thai", "tha"),
  THT = new("Tahitian", "tah"),
  TIB = new("Tibetan", "bod"),
  TKM = new("Turkmen", "tuk"),
  TMN = new("Temne", "tem"),
  TNA = new("Tswana", "tsn"),
  TNE = new("Tundra Nenets", "enh"),
  TNG = new("Tonga", "toi"),
  TOD = new("Todo", "xal"),
  TRK = new("Turkish", "tur"),
  TSG = new("Tsonga", "tso"),
  TUA = new("Turoyo Aramaic", "tru"),
  TUL = new("Tulu", "tcy"),
  TUV = new("Tuvin", "tyv"),
  TWI = new("Twi", "aka"),
  UDM = new("Udmurt", "udm"),
  UKR = new("Ukrainian", "ukr"),
  URD = new("Urdu", "urd"),
  USB = new("Upper Sorbian", "hsb"),
  UYG = new("Uyghur", "uig"),
  UZB = new("Uzbek", "uzb"),
  VEN = new("Venda", "ven"),
  VIT = new("Vietnamese", "vie"),
  WA = new("Wa", "wbm"),
  WAG = new("Wagdi", "wbr"),
  WCR = new("West-Cree", "crk"),
  WEL = new("Welsh", "cym"),
  WLF = new("Wolof", "wol"),
  XBD = new("Tai Lue", "khb"),
  XHS = new("Xhosa", "xho"),
  YAK = new("Sakha", "sah"),
  YBA = new("Yoruba", "yor"),
  YCR = new("Y-Cree", ""),
  YIC = new("Yi Classic", ""),
  YIM = new("Yi Modern", "iii"),
  ZHH = new("Chinese, Hong Kong SAR", "zho"),
  ZHP = new("Chinese Phonetic", "zho"),
  ZHS = new("Chinese Simplified", "zho"),
  ZHT = new("Chinese Traditional", "zho"),
  ZND = new("Zande", "zne"),
  ZUL = new("Zulu", "zul"),
  de = new("German found in FreeSerif.ttf", "deu"),
  nl = new("Dutch found in FreeSansBoldOblique.ttf", "nld"),
  tmh = new("Tamashek found in ebrimabd.ttf", "tmh");

    private LanguageTag(String _name, String iso3List)
    {
        String tag = name();
        while (tag.Length < 4)
        {
            tag += ' ';
        }
        this._tag = Tag.intValue(tag);
        this._name = _name;
        this._iso3List = iso3List;
    }

    public int tag()
    {
        return _tag;
    }

    public String longName()
    {
        return _name;
    }

    public boolean isDeprecated()
    {
        return this == DHV;
    }

    public IList<String> iso3List()
    {
        return Arrays.asList(_iso3List.Split(","));
    }

    public static LanguageTag fromTag(int tag)
    {
        foreach (LanguageTag script in LanguageTag.values())
        {
            if (script._tag == tag)
            {
                return script;
            }
        }
        throw new IllegalArgumentException(Tag.stringValue(tag));
    }

    private readonly int _tag;
    private readonly String _name;
    private readonly String _iso3List;
}