name: build-cake

on:
  push:
    branches: [ "main" ]
    # branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v1
      - name: Run the build script
        uses: cake-build/cake-action@v2
        with:
          script-path: build/build.cake
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./publish/
          name: publish-${{ matrix.os }}

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: build_artifacts
          pattern: publish-*
